<?php

function customviewfilters_views_data_alter(&$data){
   $data['config_taxonomy_vocabulary']['vid']['filter']['id'] = 'custom_extended_string_filter';
   $data['config_node_type']['content_type_machine_name'] = [
    'title' => t('Content type machine name'),
    'help' => t('The machine name (ID) of the content type.'),
    'field' => [
      'id' => 'content_type_machine_name',
      'field' => 'type',
    ],
    'filter' => [
      'id' => 'custom_extended_string_filter', 
      'field' => 'type',
    ],
  ];
  $data['config_taxonomy_vocabulary']['user_permission_filter'] = [
    'title' => t('Permission filter for creating terms of this vocabulary'),
    'help' => t('Only vocabularies that the selected user role or the current user can create will be shown.'),
    'filter' => [
      'id' => 'create_permission_filter',
    ],
  ];
  $data['config_node_type']['user_permission_filter'] = [
    'title' => t('Permission filter for creating nodes of this type'),
    'help' => t('Only content types that the selected user role or the current user can create will be shown.'),
    'filter' => [
      'id' => 'create_permission_filter',
    ],
  ];
}