<?php

function customviewfilters_views_data_alter(&$data){
   $data['config_taxonomy_vocabulary']['vid']['filter']['id'] = 'custom_extended_string_filter';
   $data['config_node_type']['content_type_machine_name'] = [
    'title' => t('Content type machine name'),
    'help' => t('The machine name (ID) of the content type.'),
    'field' => [
      'id' => 'content_type_machine_name',
      'field' => 'type',
    ],
    'filter' => [
      'id' => 'custom_extended_string_filter', 
      'field' => 'type',
    ],
  ];

  $data['config_taxonomy_vocabulary']['user_permission_filter'] = [
    'title' => t('Vocabulary permission filter'),
    'help' => t('Filter vocabularies based on user permissions.'),
    'filter' => [
      'id' => 'vocabulary_permission_filter',  // Je eigen filter plugin ID.
    ],
  ];

  // Zelfde voor content types (node bundles).
  $data['config_node_type']['user_permission_filter'] = [
    'title' => t('Content type permission filter'),
    'help' => t('Filter content types based on user permissions.'),
    'filter' => [
      'id' => 'bundle_permission_filter',
    ],
  ];
}