<?php

/**
 * @file
 * Main module file for Bestor Nodes Helper.
 */

use Drupal\node\NodeInterface;


/**
 * Implements hook_node_presave().
 */
function bestor_content_helper_node_presave(NodeInterface $node) {
  \Drupal::service('bestor_content_helper.node_language_analyzer')
    ->ensureDefaultTranslationTitle($node);
}


function bestor_content_helper_preprocess_menu(&$variables) {
  if ($variables['menu_name'] !== 'main') {
    return;
  }

  $disciplines_key = NULL;
  foreach ($variables['items'] as $key => $item) {
    if (isset($item['title']) && in_array($item['title'], ['Disciplines'])) {
      $disciplines_key = $key;
      break;
    }
  }

  if (!$disciplines_key) {
    return;
  }

  $facet_provider = \Drupal::service('bestor_content_helper.facet_results_provider');
  $discipline_items = $facet_provider->getFacetResultMenuItems(
    'database', 
    'facets_tax_discipline__int', 
    'discipline', 
    'page_1'
  );

  $variables['items'][$disciplines_key]['below'] = $discipline_items;
  $variables['items'][$disciplines_key]['is_expanded'] = TRUE;
}


function bestor_content_helper_node_view(array &$build, NodeInterface $node, $view_mode, $langcode) {
  $service =  \Drupal::service('bestor_content_helper.node_content_analyzer');
  $service->entityRefFieldToResultArray($node, 'field_author', 'taxonomy_term');
}