<?php

/**
 * @file
 * Main module file for Bestor Nodes Helper.
 */

use Drupal\node\NodeInterface;
use Drupal\Core\Breadcrumb\Breadcrumb;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Link;
use Drupal\Core\Url;
use Drupal\node\Entity\NodeType;
use Drupal\views\Views;
use Drupal\Core\Form\FormStateInterface;


/**
 * Implements hook_node_presave().
 */
function bestor_content_helper_node_presave(NodeInterface $node) {
  \Drupal::service('bestor_content_helper.node_language_analyzer')
    ->ensureDefaultTranslationTitle($node);
}


/**
 * Implements hook_preprocess_menu().
 */
function bestor_content_helper_preprocess_menu(&$variables) {
  if ($variables['menu_name'] !== 'main') {
    return;
  }

  $disciplines_key = NULL;
  foreach ($variables['items'] as $key => $item) {
    if (isset($item['title']) && in_array($item['title'], ['Disciplines'])) {
      $disciplines_key = $key;
      break;
    }
  }

  if (!$disciplines_key) {
    return;
  }

  $facet_provider = \Drupal::service('bestor_content_helper.facet_results_provider');
  $discipline_items = $facet_provider->getFacetResultMenuItems(
    'database', 
    'facets_tax_discipline__int', 
    'discipline', 
    'page_1'
  );

  $variables['items'][$disciplines_key]['below'] = $discipline_items;
  $variables['items'][$disciplines_key]['is_expanded'] = TRUE;
}


/**
 * Implements hook_node_view().
 */
function bestor_content_helper_node_view(array &$build, NodeInterface $node, $view_mode, $langcode) {
  $service =  \Drupal::service('bestor_content_helper.standard_node_field_processor');
  $service->getLemmaKeyData($node);
}


/**
 * Implements hook_system_breadcrumb_alter().
 */
function bestor_content_helper_system_breadcrumb_alter(Breadcrumb &$breadcrumb, RouteMatchInterface $route_match, array $context) {
    if ($node = $route_match->getParameter('node')) {
    $bundle = $node->bundle();

    $nodeContentAnalyzer =  \Drupal::service('bestor_content_helper.node_content_analyzer');
    
    $links = [];
    if ($nodeContentAnalyzer->isLemma($bundle)) {   
      $links[] = Link::createFromRoute(t('Home'), '<front>');
      $links[] = _getViewLink('database', 'page_1');
      $links[] = Link::fromTextAndUrl(
        t(NodeType::load($node->bundle())->label()), 
        Url::fromRoute('view.database.page_1', [], ['query' => ['category['. $bundle . ']' => $bundle]])
      );

    } elseif ($bundle === 'article') {
      $links[] = Link::createFromRoute(t('Home'), '<front>');
      $links[] = _getViewLink('announcements', 'page_2');
      
    } elseif ($bundle === 'event') {
      $links[] = Link::createFromRoute(t('Home'), '<front>');
      $links[] = _getViewLink('announcements', 'page_3');
    }
      
    if($links){
      $breadcrumb = new Breadcrumb();
      $breadcrumb->setLinks($links);
      $breadcrumb->addCacheContexts(['route']);
      $breadcrumb->addCacheTags(['node:' . $node->id()]);
    }
  }
}


/**
 * Implements hook_field_widget_single_element_form_alter().
 */
function  bestor_content_helper_field_widget_single_element_form_alter(array &$element, FormStateInterface $form_state, array $context) {
  // Voor paragraph edit forms
  if (empty($element['#paragraph_type']) || 
      !in_array($element['#paragraph_type'], ['media', 'text_media']) ||
      empty($element['subform']['field_cardinality_exception']) ||
      empty($element['#delta'])  
  ) {
    return;
  }

  if(isset($element['subform']['field_media_multiple'])){
    $element['subform']['field_media_multiple']['#states'] = [
      'visible' => [
        ':input[name="field_description[' . $element['#delta'] . '][subform][field_cardinality_exception][value]"]' => ['checked' => TRUE],
      ],
    ];
  }

  if(isset($element['subform']['field_media_multiple'])){
    $element['subform']['field_media']['#states'] = [
      'visible' => [
        ':input[name="field_description[' . $element['#delta'] . '][subform][field_cardinality_exception][value]"]' => ['checked' => FALSE],
      ],
    ];
  }
}


/**
 * Helper function: get url of page view by view and display id.
 */
function _getViewLink($view_id, $display_id){
  $view = Views::getView($view_id);
  $view->setDisplay($display_id);
  return Link::fromTextAndUrl(
    $view->getTitle(), 
    Url::fromRoute('view.' . $view_id . '.' . $display_id, [], [])
  );
}