<?php

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\relationship_nodes_search\Form\ExtendedIndexAddFieldsForm;


function relationship_nodes_search_entity_type_alter(array &$entity_types) {
  if (isset($entity_types['search_api_index'])) {
    $entity_types['search_api_index']->setFormClass('add_fields', ExtendedIndexAddFieldsForm::class);
  }
}

function relationship_nodes_search_search_api_field_type_mapping_alter(array &$mapping) {
 $mapping['relation_info'] = 'relationship_nodes_search_nested_relationship';
}
  
function relationship_nodes_search_theme() {
  return [
    'relationship_field' => [
      'variables' => [
        'relationships' => [],
        'grouped' => [],
        'summary' => [],
        'fields' => [],
        'row' => NULL,
      ],
      'template' => 'relationship-field',
    ],
  ];
}