cytoscape_egonetwork.settings:
  type: config_object
  label: 'Cytoscape Ego Network settings'
  mapping:
    enabled_bundles:
      type: sequence
      label: 'Enabled node bundles'
      sequence:
        type: string
        label: 'Bundle'
