name: Docker Image CI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [8.3]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set lowercase repository name
        id: repo
        run: |
          echo "name=${GITHUB_REPOSITORY#*/}" >> $GITHUB_OUTPUT
          echo "name_lc=$(echo ${GITHUB_REPOSITORY#*/} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.repo.outputs.name_lc }}:php-${{ matrix.php-version }}-v0.1.0
          push: true
          build-args: |
            PHP_VERSION=${{ matrix.php-version }}